### ISSUE TITLE
ENGINE_load* failures while building with VS 2017

### ISSUE THREAD

**Issue by hd51515** [private-octopus/picoquic#1402]
1>tls_api.c
3>socket_test.c
3>splay_test.c
1>c:\users\h3dnv\ietf\picoquic\picoquic\tls_api.c(137): error C2220: warning treated as error - no 'object' file generated
1>c:\users\h3dnv\ietf\picoquic\picoquic\tls_api.c(137): warning C4996: 'ENGINE_load_builtin_engines': Since OpenSSL 3.0
1>c:\program files\openssl-win64\include\openssl\engine.h(358): note: see declaration of 'ENGINE_load_builtin_engines'
1>c:\users\h3dnv\ietf\picoquic\picoquic\tls_api.c(138): warning C4996: 'ENGINE_register_all_ciphers': Since OpenSSL 3.0
1>c:\program files\openssl-win64\include\openssl\engine.h(395): note: see declaration of 'ENGINE_register_all_ciphers'
1>c:\users\h3dnv\ietf\picoquic\picoquic\tls_api.c(139): warning C4996: 'ENGINE_register_all_digests': Since OpenSSL 3.0
1>c:\program files\openssl-win64\include\openssl\engine.h(398): note: see declaration of 'ENGINE_register_all_digests'
1>c:\users\h3dnv\ietf\picoquic\picoquic\tls_api.c(530): warning C4996: 'ERR_get_error_line': Since OpenSSL 3.0
1>c:\program files\openssl-win64\include\openssl\err.h(411): note: see declaration of 'ERR_get_error_line'
1>token_store.c
3>stream0_frame_test.c

**Comment by huitema** [comment]
Did you install openssl 1.1?

**Comment by hd51515** [comment]
[pqvsfailure1.txt](https://github.com/private-octopus/picoquic/files/9477790/pqvsfailure1.txt)
I uploaded the full output text file here.

**Comment by hd51515** [comment]
C:\Program Files\OpenSSL-Win64\bin>openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)

**Comment by hd51515** [comment]
Looks like I have OpenSSL 3.x. I can try with 1.1 and see how it goes

**Comment by hd51515** [comment]
[vserrorswithopenssl111.txt](https://github.com/private-octopus/picoquic/files/9478155/vserrorswithopenssl111.txt)
Error count went down after downgrading to openssl1.1.1 but it still fails to build. 
On a different note: picotls seems to build only with openssl3.0. I haven't had luck to get it compiled with Openssl1.1

**Comment by hd51515** [comment]
I filed https://github.com/h2o/picotls/issues/412 for issues faced with picotls on windows with openssl1.1. May be its time to move to openssl3.0 across the board for these projects.

**Comment by hd51515** [comment]
[pqvserroropenssl111withx86win32debug.txt](https://github.com/private-octopus/picoquic/files/9478600/pqvserroropenssl111withx86win32debug.txt)

**Comment by huitema** [comment]
I agree that it would be nice to work with openssl 3.0.

For picoquic, that should not be too hard because the direct dependencies on openssl are all contained in "tls_api.c". Your X64 listing shows the errors:
```
1>c:\users\h3dnv\ietf\picoquic\picoquic\tls_api.c(133): error C2220: warning treated as error - no 'object' file generated
1>c:\users\h3dnv\ietf\picoquic\picoquic\tls_api.c(133): warning C4013: 'ERR_load_crypto_strings' undefined; assuming extern returning int
1>c:\users\h3dnv\ietf\picoquic\picoquic\tls_api.c(134): warning C4013: 'OpenSSL_add_all_algorithms' undefined; assuming extern returning int
```
That's just two lines of code. There should be a way to replace those two lines par something that works with both openssl 1.1 and 3.0.

In fact, I wonder whether there is an even simpler fix on your side. It seems that you have openssl 1.1 installed, but that when compiling tls_api.c the header files from 3.0 are used. I wonder whether there is an issue on your side with setting the include search path.

**Comment by huitema** [comment]
@hd51515 I just created PR #1403 that fixes the OpenSSL 3.0 warnings in Ubuntu 22.04, but I have not tested it in Windows. Can you verify that it does fix your issue?

**Comment by huitema** [comment]
Seems to be working now.
